"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar.jsx";
import LoginModal from "@/components/LoginModal.jsx";
import { useGenerationStore } from "@/state/idea-generation.js";
import SignUpModal from "@/components/SignUpModal.jsx";
import LogoutModal from "@/components/LogoutModal.jsx";
import HamburgerMenu from "@/components/HamburgerMenu.jsx";
import CreateCommunityModal from "@/components/CreateCommunityModal.jsx";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const { openLoginModal } = useGenerationStore();
  const { openSignUpModal } = useGenerationStore();
  const { openLogoutModal } = useGenerationStore();
  const { openHamburgerMenu } = useGenerationStore();
  const { openCreateCommunityModal } = useGenerationStore();

  return (
    <html lang="en">
      <body className={inter.className}>
        {openLoginModal ? (
          <LoginModal />
        ) : openSignUpModal ? (
          <SignUpModal />
        ) : openCreateCommunityModal ? (
          <CreateCommunityModal />
        ) 
        : (
          <>
            <Navbar />
            <div id="child">{children}</div>
            {openLogoutModal && <LogoutModal />}
            {openHamburgerMenu && <HamburgerMenu />}
          </>
        )}
      </body>
    </html>
  );
}
